//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationMaster.UI.Maui.Common {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IrrigationMaster.UI.Maui.Common.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo de conexión con el servidor..
        /// </summary>
        public static string ApiConnectionError {
            get {
                return ResourceManager.GetString("ApiConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención.
        /// </summary>
        public static string AttentionTitle {
            get {
                return ResourceManager.GetString("AttentionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abriendo Panel de Configuración de Caudal y Tiempos....
        /// </summary>
        public static string CaudalConfigLoading {
            get {
                return ResourceManager.GetString("CaudalConfigLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consola Maestra.
        /// </summary>
        public static string ConsoleTitle {
            get {
                return ResourceManager.GetString("ConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Acceso.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accediendo al Historial Auditado de Riego....
        /// </summary>
        public static string HistoryLogLoading {
            get {
                return ResourceManager.GetString("HistoryLogLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accediendo a la Configuración de Infraestructura Raíz....
        /// </summary>
        public static string InfrastructureLoading {
            get {
                return ResourceManager.GetString("InfrastructureLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu Presidente ha sido notificado..
        /// </summary>
        public static string IncidentReportedSuccess {
            get {
                return ResourceManager.GetString("IncidentReportedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cargando el Estado de Andadores en Tiempo Real....
        /// </summary>
        public static string LiveStatusLoading {
            get {
                return ResourceManager.GetString("LiveStatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, introduce tu email y contraseña para entrar..
        /// </summary>
        public static string LoginValidationWarning {
            get {
                return ResourceManager.GetString("LoginValidationWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Introduce un código de invitación válido (mínimo 8 caracteres)..
        /// </summary>
        public static string MsgInvalidInvitationCode {
            get {
                return ResourceManager.GetString("MsgInvalidInvitationCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Abriendo la Supervisión de Colas FIFO por Andador....
        /// </summary>
        public static string ManageQueuesLoading {
            get {
                return ResourceManager.GetString("ManageQueuesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, escribe el mensaje del aviso antes de enviarlo..
        /// </summary>
        public static string MsgMissingBroadcastMessage {
            get {
                return ResourceManager.GetString("MsgMissingBroadcastMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, describe la incidencia antes de enviarla..
        /// </summary>
        public static string MsgMissingIncidentDescription {
            get {
                return ResourceManager.GetString("MsgMissingIncidentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa todos los datos de la organización..
        /// </summary>
        public static string MsgMissingOrgData {
            get {
                return ResourceManager.GetString("MsgMissingOrgData", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa los tres campos de contraseña..
        /// </summary>
        public static string MsgMissingPasswordData {
            get {
                return ResourceManager.GetString("MsgMissingPasswordData", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa todos los datos obligatorios del registro..
        /// </summary>
        public static string MsgMissingRegisterData {
            get {
                return ResourceManager.GetString("MsgMissingRegisterData", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa los dos campos de contraseña..
        /// </summary>
        public static string MsgMissingResetPasswordData {
            get {
                return ResourceManager.GetString("MsgMissingResetPasswordData", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa todos los datos del sector hidráulico..
        /// </summary>
        public static string MsgMissingSectorData {
            get {
                return ResourceManager.GetString("MsgMissingSectorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa todos los datos del andador..
        /// </summary>
        public static string MsgMissingWalkwayData {
            get {
                return ResourceManager.GetString("MsgMissingWalkwayData", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La nueva contraseña y su confirmación no coinciden..
        /// </summary>
        public static string MsgPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("MsgPasswordsDoNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona a quién quieres avisar antes de enviarlo..
        /// </summary>
        public static string MsgSelectAudienceFirst {
            get {
                return ResourceManager.GetString("MsgSelectAudienceFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un rol antes de confirmar el cambio..
        /// </summary>
        public static string MsgSelectRoleFirst {
            get {
                return ResourceManager.GetString("MsgSelectRoleFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Autenticación correcta, pero falló la carga de la interfaz de administración..
        /// </summary>
        public static string NavigationFallbackError {
            get {
                return ResourceManager.GetString("NavigationFallbackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo establecer comunicación con el túnel de desarrollo. Verifica tu red..
        /// </summary>
        public static string NetworkConnectionError {
            get {
                return ResourceManager.GetString("NetworkConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo conectar con el servidor. Revisa tu conexión o el estado del túnel..
        /// </summary>
        public static string NetworkFallbackError {
            get {
                return ResourceManager.GetString("NetworkFallbackError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Aviso enviado a {0} destinatarios..
        /// </summary>
        public static string NotificationSentSuccessFormat {
            get {
                return ResourceManager.GetString("NotificationSentSuccessFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones marcadas como leídas..
        /// </summary>
        public static string NotificationsMarkedAllReadSuccess {
            get {
                return ResourceManager.GetString("NotificationsMarkedAllReadSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear la organización en el servidor..
        /// </summary>
        public static string OrgCreatedError {
            get {
                return ResourceManager.GetString("OrgCreatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organización creada con éxito..
        /// </summary>
        public static string OrgCreatedSuccess {
            get {
                return ResourceManager.GetString("OrgCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actualizada con éxito..
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña restablecida con éxito..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Abriendo el Editor de Alertas y Comunicados....
        /// </summary>
        public static string PublishIncidentsLoading {
            get {
                return ResourceManager.GetString("PublishIncidentsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el sector hidráulico..
        /// </summary>
        public static string SectorCreatedError {
            get {
                return ResourceManager.GetString("SectorCreatedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Rol actualizado con éxito..
        /// </summary>
        public static string RoleChangedSuccess {
            get {
                return ResourceManager.GetString("RoleChangedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Sector Hidráulico creado con éxito..
        /// </summary>
        public static string SectorCreatedSuccess {
            get {
                return ResourceManager.GetString("SectorCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error del servidor (Código:.
        /// </summary>
        public static string ServerErrorCode {
            get {
                return ResourceManager.GetString("ServerErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accediendo a los parámetros técnicos del sistema....
        /// </summary>
        public static string SettingsLoading {
            get {
                return ResourceManager.GetString("SettingsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Sistema.
        /// </summary>
        public static string SystemErrorTitle {
            get {
                return ResourceManager.GetString("SystemErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Turno terminado con éxito..
        /// </summary>
        public static string TurnCompletedSuccess {
            get {
                return ResourceManager.GetString("TurnCompletedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Turno iniciado con éxito..
        /// </summary>
        public static string TurnStartedSuccess {
            get {
                return ResourceManager.GetString("TurnStartedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado al procesar la solicitud..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tu cuenta fue creada. Un administrador debe aprobarla antes de que puedas iniciar sesión..
        /// </summary>
        public static string UserRegisteredSuccess {
            get {
                return ResourceManager.GetString("UserRegisteredSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Usuario aprobado con éxito..
        /// </summary>
        public static string UserApprovedSuccess {
            get {
                return ResourceManager.GetString("UserApprovedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Andador actualizado con éxito..
        /// </summary>
        public static string WalkwayAssignedSuccess {
            get {
                return ResourceManager.GetString("WalkwayAssignedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error al registrar el andador..
        /// </summary>
        public static string WalkwayCreatedError {
            get {
                return ResourceManager.GetString("WalkwayCreatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Andador registrado con éxito..
        /// </summary>
        public static string WalkwayCreatedSuccess {
            get {
                return ResourceManager.GetString("WalkwayCreatedSuccess", resourceCulture);
            }
        }
    }
}
