<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Api\Handlers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IrrigationMaster.Mobile.Core\IrrigationMaster.Mobile.Core.csproj" />
  </ItemGroup>

</Project>
