<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Api\Handlers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IrrigationMaster.Mobile.Application\IrrigationMaster.Mobile.Application.csproj" />
  </ItemGroup>

</Project>
